-- Generated by scripts/export-seed-sql.mjs from web/js/seedData.js. Do not edit by hand.
-- Safe to re-run: it replaces sample rows (and their plan days) and never touches real (is_sample = false) rows or check-ins.
begin;
delete from public.resources where is_sample;

insert into public.resources (type, title, subtitle, body, url, contact, area, duration_min, tags, is_sample) values
('scripture', 'Psalm 34:18', null, 'The LORD is close to the brokenhearted and saves those who are crushed in spirit.', null, null, null, null, array['shame', 'brokenness', 'despair'], true),
('scripture', 'Romans 8:1', null, 'Therefore, there is now no condemnation for those who are in Christ Jesus.', null, null, null, null, array['shame', 'guilt', 'identity'], true),
('scripture', '1 Corinthians 10:13', null, 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear, but when you are tempted, he will also provide a way out so that you can endure it.', null, null, null, null, array['temptation', 'struggle', 'hope'], true),
('scripture', 'James 5:16', null, 'Therefore confess your sins to each other and pray for each other so that you may be healed.', null, null, null, null, array['accountability', 'community', 'confession'], true),
('scripture', '2 Corinthians 5:17', null, 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!', null, null, null, null, array['identity', 'freedom', 'hope'], true),
('scripture', 'Galatians 6:2', null, 'Carry each other''s burdens, and in this way you will fulfill the law of Christ.', null, null, null, null, array['community', 'accountability', 'support'], true),
('scripture', 'Psalm 139:23-24', null, 'Search me, God, and know my heart; test me and know my anxious thoughts. See if there is any offensive way in me, and lead me in the way everlasting.', null, null, null, null, array['struggle', 'honesty', 'growth'], true),
('scripture', 'Lamentations 3:22-23', null, 'Because of the LORD''s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.', null, null, null, null, array['hope', 'relapse', 'perseverance'], true),
('scripture', 'Ephesians 2:8-9', null, 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast.', null, null, null, null, array['grace', 'identity', 'shame'], true),
('scripture', 'Psalm 23:4', null, 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.', null, null, null, null, array['loneliness', 'hope', 'struggle'], true),
('scripture', 'Philippians 4:6-7', null, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.', null, null, null, null, array['anxiety', 'stress', 'in-the-moment'], true),
('scripture', '1 John 1:9', null, 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.', null, null, null, null, array['confession', 'grace', 'relapse'], true),
('scripture', 'Isaiah 41:10', null, 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.', null, null, null, null, array['stress', 'struggle', 'hope'], true),
('scripture', 'Romans 12:2', null, 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God''s will is — his good, pleasing and perfect will.', null, null, null, null, array['growth', 'renewal', 'triggers'], true),
('scripture', 'Hebrews 4:15-16', null, 'For we do not have a high priest who is unable to empathize with our weaknesses, but we have one who has been tempted in every way, just as we are — yet he did not sin. Let us then approach God''s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.', null, null, null, null, array['grace', 'struggle', 'temptation'], true),
('scripture', 'Psalm 51:10', null, 'Create in me a pure heart, O God, and renew a steadfast spirit within me.', null, null, null, null, array['renewal', 'confession', 'growth'], true),
('sermon', 'Freedom from Shame', 'Example Pastor A. Reyes · Restored', null, '#', null, null, 34, array['shame', 'freedom'], true),
('sermon', 'Walking in the Light', 'Example Pastor J. Whitfield · Honest Faith', null, '#', null, null, 28, array['honesty', 'accountability'], true),
('sermon', 'You Are Not Your Worst Day', 'Example Pastor M. Osei · Identity in Christ', null, '#', null, null, 41, array['identity', 'shame'], true),
('sermon', 'When Willpower Isn''t Enough', 'Example Pastor R. Diaz · Grace Over Grit', null, '#', null, null, 37, array['struggle', 'grace', 'relapse'], true),
('sermon', 'The Power of Being Known', 'Example Pastor L. Kim · Community', null, '#', null, null, 31, array['community', 'accountability', 'loneliness'], true),
('sermon', 'Fighting for Purity', 'Example Pastor T. Brooks · Battle Ready', null, '#', null, null, 39, array['triggers', 'temptation'], true),
('sermon', 'The Loneliness Trap', 'Example Pastor S. Nguyen · Better Together', null, '#', null, null, 33, array['loneliness', 'community'], true),
('sermon', 'From Shame to Sonship', 'Example Pastor D. Coleman · Identity in Christ', null, '#', null, null, 36, array['shame', 'identity'], true),
('sermon', 'Small Steps, Real Freedom', 'Example Pastor A. Reyes · Restored', null, '#', null, null, 30, array['perseverance', 'growth'], true),
('sermon', 'What Grace Actually Means', 'Example Pastor J. Whitfield · Honest Faith', null, '#', null, null, 27, array['grace', 'relapse'], true),
('article', 'Understanding the Brain Science of Pornography Addiction', 'Example author: Dr. S. Patton', 'A plain-language look at how compulsive pornography use affects the brain''s reward pathways, and why willpower alone often isn''t enough to break the cycle.', '#', null, null, null, array['struggle', 'education'], true),
('article', 'How to Talk to Your Spouse About This Struggle', 'Example author: C. Bennett, LMFT', 'Practical guidance for having an honest, non-defensive conversation with a spouse or partner about pornography use — timing, wording, and what to expect.', '#', null, null, null, array['community', 'honesty', 'relationships'], true),
('article', 'Why Accountability Partners Work', 'Example author: Reclaim Editorial', 'The research and reasoning behind why regular check-ins with another person measurably improve recovery outcomes.', '#', null, null, null, array['accountability', 'community'], true),
('article', 'Recognizing Your Triggers', 'Example author: Reclaim Editorial', 'A guide to identifying the emotional states, times of day, and situations that most often precede a slip — the first step toward interrupting the pattern.', '#', null, null, null, array['struggle', 'triggers', 'relapse'], true),
('article', 'The Role of Community in Recovery', 'Example author: Reclaim Editorial', 'Why isolation is one of the strongest predictors of relapse, and what meaningfully re-engaging with community can look like in practice.', '#', null, null, null, array['community', 'loneliness'], true),
('article', 'What the Research Says About Recovery Rates', 'Example author: Dr. S. Patton', 'An honest look at what studies actually show about relapse and long-term recovery — and why consistent support structures change the odds more than any single tactic.', '#', null, null, null, array['struggle', 'education', 'hope'], true),
('article', 'Setting Up Accountability Software the Right Way', 'Example author: Reclaim Editorial', 'A practical walkthrough of configuring screen accountability tools so they actually get used — who should receive reports, how often, and how to talk about it upfront.', '#', null, null, null, array['accountability', 'triggers'], true),
('article', 'Talking to Your Kids About This (When They''re Old Enough)', 'Example author: C. Bennett, LMFT', 'Age-appropriate guidance for parents who want to have an honest, non-shaming conversation with older kids or teens about pornography.', '#', null, null, null, array['community', 'honesty'], true),
('article', 'When Your Spouse Found Out: A Guide for the First 48 Hours', 'Example author: C. Bennett, LMFT', 'What to do and not do in the immediate aftermath of disclosure — for both partners — while bigger conversations and counseling get scheduled.', '#', null, null, null, array['community', 'honesty', 'relationships'], true),
('article', 'Boredom, Stress, and the Brain''s Reward Loop', 'Example author: Dr. S. Patton', 'Why boredom and stress are two of the most common relapse triggers, and what''s actually happening neurologically when they show up.', '#', null, null, null, array['triggers', 'stress', 'education'], true),
('devotional', 'Today''s Battle Isn''t Yours Alone', null, 'A short reflection on 1 Corinthians 10:13 — that every temptation comes with a way out, even when it doesn''t feel like it in the moment.', null, null, null, null, array['temptation', 'hope'], true),
('devotional', 'When Shame Lies to You', null, 'Shame tells you to hide. Grace says come closer. A short reflection on Romans 8:1 and what it means to stop hiding.', null, null, null, null, array['shame', 'grace'], true),
('devotional', 'Small Steps, Real Change', null, 'Recovery rarely looks like a single dramatic moment — it looks like a thousand small, boring, faithful choices. A reflection on perseverance.', null, null, null, null, array['perseverance', 'growth'], true),
('devotional', 'The God Who Sees You', null, 'A short reflection on being fully known and fully loved anyway, drawing on the story of Hagar in Genesis 16.', null, null, null, null, array['identity', 'shame'], true),
('devotional', 'Grace for the Relapse', null, 'A slip is not the end of the story. A reflection on Lamentations 3:22-23 — new mercies, every morning, including this one.', null, null, null, null, array['relapse', 'grace', 'hope'], true),
('devotional', 'Today You Get to Choose Again', null, 'Yesterday doesn''t get a vote in today. A short reflection on starting fresh without pretending the past didn''t happen.', null, null, null, null, array['perseverance', 'hope'], true),
('devotional', 'The Loneliness Lie', null, 'Isolation tells you no one would understand. A reflection on why that''s almost never true, and what one honest conversation can do.', null, null, null, null, array['loneliness', 'community'], true),
('devotional', 'Grace Isn''t a Loophole', null, 'Grace isn''t permission to keep drifting — it''s the strength to actually change. A short reflection on Hebrews 4:16.', null, null, null, null, array['grace', 'accountability'], true),
('devotional', 'You Are Not Behind', null, 'There''s no finish line you''re late to. A reflection on why comparing your recovery timeline to anyone else''s misses the point.', null, null, null, null, array['growth', 'relapse'], true),
('devotional', 'Held, Not Hunted', null, 'Anxiety can make God''s attention feel like scrutiny. A short reflection on Psalm 23 — being watched over, not watched for failure.', null, null, null, null, array['anxiety', 'identity'], true),
('coping_mechanism', 'Urge Surfing', null, 'Urges peak and fade, usually within 15-20 minutes, whether or not you act on them. Instead of fighting the urge, try noticing it like a wave: name it, sit with it, and let it crest and pass without acting.', null, null, null, null, array['temptation', 'in-the-moment'], true),
('coping_mechanism', 'The HALT Check', null, 'Before reacting to an urge, ask: am I Hungry, Angry, Lonely, or Tired? Urges are often a stand-in for one of these unmet needs. Naming the real need can point you to the real fix.', null, null, null, null, array['triggers', 'in-the-moment'], true),
('coping_mechanism', 'Change Your Environment', null, 'Physically move — leave the room, go outside, go where other people are. Removing yourself from the location tied to the urge breaks the pattern more reliably than trying to white-knuckle it in place.', null, null, null, null, array['in-the-moment', 'triggers'], true),
('coping_mechanism', 'Reach Out Immediately', null, 'Text or call your accountability partner the moment you notice an urge, not after. Saying it out loud to another person changes the moment.', null, null, null, null, array['accountability', 'in-the-moment'], true),
('coping_mechanism', '5-4-3-2-1 Grounding', null, 'Name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste. A simple sensory grounding technique to interrupt an escalating moment.', null, null, null, null, array['in-the-moment', 'anxiety'], true),
('coping_mechanism', 'Move Your Body', null, 'A short walk, push-ups, or any physical exertion changes your physiological state and can interrupt an urge cycle faster than willpower alone.', null, null, null, null, array['in-the-moment', 'stress'], true),
('coping_mechanism', 'Cold Water Reset', null, 'Splash cold water on your face or hold an ice cube for 30 seconds. The physical shock is a genuine physiological pattern interrupt, not just a distraction trick.', null, null, null, null, array['in-the-moment', 'stress'], true),
('coping_mechanism', 'Have a Reach-Out Script Ready', null, 'Write out a short text to your accountability partner in advance — something like "Having an urge, could use a check-in" — so you don''t have to compose a message in the hardest moment. Save it as a note you can copy-paste.', null, null, null, null, array['accountability', 'in-the-moment'], true),
('coping_mechanism', 'The 10-Minute Rule', null, 'Commit to waiting just 10 minutes before acting on the urge — no other rules. Urges are time-limited, and a 10-minute delay is often enough for the intensity to drop and your judgment to come back online.', null, null, null, null, array['in-the-moment', 'temptation'], true),
('coping_mechanism', 'Shift What You''re Hearing', null, 'Put on music, a podcast, or worship that pulls your attention elsewhere. Changing your auditory environment is a fast, low-effort way to break focus on the urge.', null, null, null, null, array['in-the-moment', 'triggers'], true),
('coping_mechanism', 'Anchor Verse', null, 'Memorize one short verse ahead of time and say it out loud when an urge hits — 1 Corinthians 10:13 works well for this. Having it ready beats trying to think of something in the moment.', null, null, null, null, array['in-the-moment', 'temptation'], true),
('coping_mechanism', 'Write Down What Led Here', null, 'Right when you notice the urge — before or after acting on it — jot down what happened in the hour before: mood, place, what you were avoiding. Patterns are much easier to see on paper than in memory.', null, null, null, null, array['triggers', 'growth'], true),
('small_group', 'Men of Grace Recovery Group', 'New Hope Community Church', 'Tuesdays, 7:00 PM · In-person', null, '(555) 201-4488', 'Example — Grove City, PA', null, '{}', true),
('small_group', 'Fresh Start Men''s Circle', 'Cornerstone Fellowship', 'Thursdays, 6:30 PM · In-person', null, '(555) 774-2201', 'Example — Pittsburgh, PA', null, '{}', true),
('small_group', 'Freedom Online Group', 'Multi-church partnership', 'Sundays, 8:00 PM (Zoom) · Online', null, '(555) 990-1122', 'Example — Online / Nationwide', null, '{}', true),
('small_group', 'New Life Men''s Fellowship', 'Riverbend Community Church', 'Wednesdays, 7:00 PM · In-person', null, '(555) 328-1145', 'Example — Columbus, OH', null, '{}', true),
('small_group', 'Renewed Hearts Women''s Group', 'Grace Chapel', 'Mondays, 7:30 PM (Zoom) · Online', null, '(555) 552-9013', 'Example — Online / Nationwide', null, '{}', true),
('accountability_program', 'Reclaim Accountability Partner Matching', null, 'Pairs you with a trained, same-gender accountability partner for regular check-ins.', null, '(555) 340-9981', null, null, '{}', true),
('accountability_program', 'Covenant Eyes-style Accountability Software', null, 'Screen accountability software that sends activity reports to a partner you choose.', null, 'example-accountability.test', null, null, '{}', true),
('accountability_program', 'Trusted Friend Check-In Network', null, 'A simple, low-tech option: a rotating list of volunteers willing to receive a text or call check-in from someone they don''t know personally, no software required.', null, '(555) 276-4420', null, null, '{}', true),
('accountability_program', 'Ministry Mentor Program', null, 'Pairs you with an older, more experienced mentor (not just a peer) for longer-term accountability and guidance, typically meeting every other week.', null, '(555) 918-3367', null, null, '{}', true),
('counseling_center', 'Grace & Truth Counseling Center', 'Faith-based licensed counseling', null, null, '(555) 412-8890', 'Example — Grove City, PA', null, '{}', true),
('counseling_center', 'Pure Freedom Telehealth Counseling', 'Licensed counseling, addiction-informed, telehealth', null, null, '(555) 665-3320', 'Example — Nationwide (telehealth)', null, '{}', true),
('counseling_center', 'Renewal Family Counseling', 'Licensed counseling, individual and couples', null, null, '(555) 704-2298', 'Example — Columbus, OH', null, '{}', true),
('counseling_center', 'Overcomers Telehealth Group Therapy', 'Licensed group therapy, addiction-focused, telehealth', null, null, '(555) 833-5561', 'Example — Nationwide (telehealth)', null, '{}', true);

with plan as (insert into public.resources (type, title, subtitle, body, url, contact, area, duration_min, tags, is_sample) values ('bible_plan', '7 Days on Freedom from Shame', null, 'A one-week reading plan working through what it means to be free from shame and condemnation.', null, null, null, null, array['shame', 'freedom'], true) returning id)
insert into public.bible_plan_days (plan_id, day_number, reference, reflection)
select plan.id, d.day_number, d.reference, d.reflection from plan, (values
    (1, 'Romans 8:1-2', 'There is no condemnation. Start here, not at the end.'),
    (2, 'Psalm 32:3-5', 'What happens when we stop hiding and confess honestly.'),
    (3, 'Genesis 3:8-10', 'Shame''s oldest move is hiding. Notice where you hide.'),
    (4, 'Luke 15:17-24', 'The prodigal''s return — grace runs toward you, not away.'),
    (5, '2 Corinthians 5:17', 'New creation, not a patched-up old one.'),
    (6, 'John 8:1-11', 'Neither do I condemn you — go, and sin no more.'),
    (7, 'Zephaniah 3:17', 'God rejoicing over you — not disappointed, rejoicing.')
) as d(day_number, reference, reflection);

with plan as (insert into public.resources (type, title, subtitle, body, url, contact, area, duration_min, tags, is_sample) values ('bible_plan', '14 Days Building New Habits', null, 'A two-week plan pairing scripture with practical reflection on replacing old patterns with new ones.', null, null, null, null, array['growth', 'perseverance'], true) returning id)
insert into public.bible_plan_days (plan_id, day_number, reference, reflection)
select plan.id, d.day_number, d.reference, d.reflection from plan, (values
    (1, 'Romans 12:2', 'Renewing your mind is a process, not an event.'),
    (2, 'Philippians 4:8', 'What you dwell on shapes what you do.'),
    (3, 'Galatians 5:16-17', 'The pull of competing desires is real and named here.'),
    (4, '1 Corinthians 6:12', 'Not everything permissible is beneficial.'),
    (5, 'Hebrews 12:1-2', 'Throw off what hinders — running the race with endurance.'),
    (6, 'Proverbs 4:23', 'Guard your heart; it''s the wellspring of everything else.'),
    (7, 'Psalm 1:1-3', 'What you plant yourself near shapes what grows in you.'),
    (8, 'Ecclesiastes 4:9-10', 'Two are better than one — the case for not doing this alone.'),
    (9, 'James 1:14-15', 'How temptation actually develops, honestly described.'),
    (10, 'Matthew 26:41', 'Watch and pray, so you won''t fall into temptation.'),
    (11, '1 Peter 5:8-9', 'Staying alert without becoming anxious.'),
    (12, 'Isaiah 40:29-31', 'Strength for the weary — this is who it''s for.'),
    (13, 'Philippians 1:6', 'He who began a good work will carry it to completion.'),
    (14, 'Psalm 40:1-3', 'A new song, after the waiting — looking back at 14 days.')
) as d(day_number, reference, reflection);

with plan as (insert into public.resources (type, title, subtitle, body, url, contact, area, duration_min, tags, is_sample) values ('bible_plan', '10 Days on Identity in Christ', null, 'A ten-day plan for untangling who you are from what you''ve done — working through identity, not just behavior.', null, null, null, null, array['identity', 'shame', 'grace'], true) returning id)
insert into public.bible_plan_days (plan_id, day_number, reference, reflection)
select plan.id, d.day_number, d.reference, d.reflection from plan, (values
    (1, 'Genesis 1:27', 'Made in the image of God — before any of this happened.'),
    (2, 'Ephesians 2:8-9', 'A gift, not a performance you''re being graded on.'),
    (3, '1 Peter 2:9', 'Chosen, not merely tolerated.'),
    (4, 'Romans 8:38-39', 'Nothing separates you from this love — read the whole list.'),
    (5, 'Galatians 2:20', 'A new center of identity, not a self-improvement project.'),
    (6, 'Colossians 3:1-3', 'Your life is hidden — safe — not exposed and disqualified.'),
    (7, '2 Corinthians 5:17', 'Revisit this one. Let it actually land this time.'),
    (8, 'Psalm 139:13-14', 'Fearfully and wonderfully made — including the parts you''re hardest on.'),
    (9, '1 John 3:1', 'Called children of God. Not almost. Not on probation.'),
    (10, 'Philippians 3:12-14', 'Pressing on — identity settled, growth still ongoing.')
) as d(day_number, reference, reflection);

with plan as (insert into public.resources (type, title, subtitle, body, url, contact, area, duration_min, tags, is_sample) values ('bible_plan', '5 Days When You''ve Just Slipped', null, 'A short plan for right after a slip — not to dwell on failure, but to get grounded again quickly and take the next honest step.', null, null, null, null, array['relapse', 'grace', 'hope'], true) returning id)
insert into public.bible_plan_days (plan_id, day_number, reference, reflection)
select plan.id, d.day_number, d.reference, d.reflection from plan, (values
    (1, '1 John 1:9', 'Confess it plainly. No decoration, no minimizing.'),
    (2, 'Lamentations 3:22-23', 'New mercy this morning — today counts as a fresh one.'),
    (3, 'Psalm 51:10-12', 'Ask for a clean heart, not just less guilt.'),
    (4, 'James 5:16', 'Tell someone. Today, not eventually.'),
    (5, 'Isaiah 43:18-19', 'Forget the former things — a new thing is starting, right now.')
) as d(day_number, reference, reflection);

commit;
